openapi: 3.0.0
info:
  contact:
    name: demo
    email: demo@axway.com
  title: 'amazon coupon api'
  version: '1.0'
  description: 'https://api.amazon.com/coupon/ specs'
servers:
  - url: 'https://ptx136.demo.axway.com:8081/'
tags:
  - name: coupon
  - name: 'amazon'
paths:
  /coupon:
    get:
      summary: Get a amazon coupon
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/amazonCoupon'
              examples: {}
      operationId: get-amazon-coupon
      description: Get a coupon for amazon
    parameters: []
components:
  schemas:
    amazonDateRange:
      title: DateRange
      type: object
      properties:
        start:
          type: string
          x-faker: date.past
        end:
          type: string
          x-faker: date.future
    amazonCoupon:
      title: Coupon
      type: object
      x-examples: {}
      properties:
        id:
          type: string
          pattern: '[0-9]{7}'
        code:
          type: string
          enum:
            - SPRINGOFF
            - BACKTOSCHOOL
            - XMASGIFT
            - SUMMERTIME
            - HLLWN
            - MOTHERSDAY
            - FATHERSDAY
            - SWAG_ON
            - JUSTDOIT
        validity:
          $ref: '#/components/schemas/amazonDateRange'
        amount:
          type: string
          enum:
            - 10€
            - 20€
            - 5€
            - 15€
        recipient:
          type: string
          x-faker: internet.email
          format: email
  securitySchemes: {}
  examples: {}
