name: Deploy all Insurtech APIs

on:
  push:
    branches:
      - demo
    paths: insurtech/**

jobs:
  Insurtech-API-Deployment:
    if: "!contains(github.event.head_commit.message, '[SKIP-CI]')" 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api:
          - gfgl
          - healthbreach
          - payl
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v2
      - name: Generate api-config.json
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i -y
      - run: npx json-merger insurtech/${{ matrix.api }}/api-config-tpl.json |jq . > insurtech/${{ matrix.api }}/api-config.json
      - name: Publish to APIM
        uses: Axway/presales-apim-cli-action@v0
        env:
          APIM_USER: ${{ secrets.APIM_USER }}
          APIM_PASS: ${{ secrets.APIM_PASS }}
          APIM_HOST: ${{ secrets.APIM_HOST }}
          APIM_PORT: ${{ secrets.APIM_PORT }}
        with:
          command: api import -c insurtech/${{ matrix.api }}/api-config.json